runtime: php  # language of the app
env: flex     # let app engine know we use flexible environment

runtime_config:
 document_root: public   #folder where index.php is

# Ensure we skip ".env", which is only for local development
skip_files:
 - .env #we want to skip this to make sure we don’t mess stuff up on the server

env_variables:
  DB_CONNECTION: mysql
  DB_HOST: 35.193.17.141
  DB_PORT: 3306
  DB_DATABASE: healthshopper
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_SOCKET: /cloudsql/healthshopper-204407:us-central1:healthshopper
  
 # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:HRb93M+D7BHO2GX5U1/4xmCO6xMvAGp5k56B+GoquW8=
  STORAGE_DIR: /database
#go to generate app key paragraf in this tutorial


beta_settings:
   # for Cloud SQL, set this value to the Cloud SQL connection name,
   # e.g. "project:region:cloudsql-instance"
   cloud_sql_instances: healthshopper-204407:us-central1:healthshopper
   
   
   